import dotenv from "dotenv";
import supabase from "../config/supabase.js";

dotenv.config();

// Dữ liệu tài sản
const ASSETS_DATA = [
  {
    id: "03661392-8b00-475e-b9e3-eeb7ff2892b7",
    asset_code: "SL.MSI21",
    product_name: "MSI Modern 14 B11MOU-1034VN",
    category: "laptop",
    model: "MSI Modern 14 B11MOU-1034VN",
    color: null,
    serial_number: "SN-SL.MSI21-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: i5-1155G7 | RAM: 8 GB | VGA: Intel Iris Xe Graphics | SSD: 512 GB",
    department: "General",
  },
  {
    id: "0a31cbeb-d36a-4137-a7f1-a0257dab7a25",
    asset_code: "SL.THI26",
    product_name: "Thinkpad T14 Gen 2 2021",
    category: "laptop",
    model: "Thinkpad T14 Gen 2 2021",
    color: null,
    serial_number: "SN-SL.THI26-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: AMD Ryzen 7 Pro 5850 | RAM: 32 GB | VGA: Integrated AMD Radeon Graphics | SSD: 512 GB",
    department: "General",
  },
  {
    id: "19068747-55a3-4a7f-9293-26a4fe1c391e",
    asset_code: "SL.THI9",
    product_name: "ThinkPad T470",
    category: "laptop",
    model: "ThinkPad T470",
    color: null,
    serial_number: "SN-SL.THI9-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: I7-7600U | RAM: 8 GB | VGA: Intel HD Graphics 620 | SSD: 256 GB",
    department: "General",
  },
  {
    id: "313be8b3-51a9-4c44-aa6f-450b8390916d",
    asset_code: "SL.MSI29",
    product_name: "MSI Modern 14 B11MOU-1034VN",
    category: "laptop",
    model: "MSI Modern 14 B11MOU-1034VN",
    color: null,
    serial_number: "SN-SL.MSI29-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: i5-1155G7 | RAM: 16 GB | VGA: Intel Iris Xe Graphics | SSD: 512 GB",
    department: "General",
  },
  {
    id: "3b084e56-aec1-4bdf-84d7-75a2807ad2b1",
    asset_code: "SL.MAC18",
    product_name: "Macbook Pro 13 inch 2020",
    category: "laptop",
    model: "Macbook Pro 13 inch 2020",
    color: null,
    serial_number: "SN-SL.MAC18-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes: "CPU: M1 | RAM: 16 GB | VGA: Apple M1 GPU | SSD: 256 GB",
    department: "General",
  },
  {
    id: "46521cf1-2794-4be2-9d9a-1ff4d400f497",
    asset_code: "SL.SUR24",
    product_name: "Microsoft Surface Pro 8",
    category: "laptop",
    model: "Microsoft Surface Pro 8",
    color: null,
    serial_number: "SN-SL.SUR24-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: i5 11th | RAM: 16 GB | VGA: Intel Iris Xe Graphics | SSD: 256 GB",
    department: "General",
  },
  {
    id: "4dcbafb7-8204-4ae0-9143-4f7db0ab6cac",
    asset_code: "SL.MSI28",
    product_name: "MSI Modern 14 B11MOU-1034VN",
    category: "laptop",
    model: "MSI Modern 14 B11MOU-1034VN",
    color: null,
    serial_number: "SN-SL.MSI28-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: i5-1155G7 | RAM: 16 GB | VGA: Intel Iris Xe Graphics | SSD: 512 GB",
    department: "General",
  },
  {
    id: "5d081f52-885c-4d4d-85dd-5b162db168c5",
    asset_code: "SL.MAC4",
    product_name: "Macbook Pro",
    category: "laptop",
    model: "Macbook Pro",
    color: null,
    serial_number: "SN-SL.MAC4-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes: null,
    department: "General",
  },
  {
    id: "67de578f-cdc1-4d31-8ee8-d78a98deca12",
    asset_code: "SL.THI8",
    product_name: "ThinkPad T470",
    category: "laptop",
    model: "ThinkPad T470",
    color: null,
    serial_number: "SN-SL.THI8-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: I7-7600U | RAM: 8 GB | VGA: Intel HD Graphics 620 | SSD: 256 GB",
    department: "General",
  },
  {
    id: "6e185861-d009-406a-940b-d8905d9ae4bc",
    asset_code: "SL.MSI15",
    product_name: "MSI Modern 14 B11MOU-1034VN",
    category: "laptop",
    model: "MSI Modern 14 B11MOU-1034VN",
    color: null,
    serial_number: "SN-SL.MSI15-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: i5-1155G7 | RAM: 16 GB | VGA: Intel Iris Xe Graphics | SSD: 512 GB",
    department: "General",
  },
  {
    id: "6e1f704b-131d-41bd-9cae-585728b73e75",
    asset_code: "SL.MSI8",
    product_name: "MSI Modern 14 B11MOU-1034VN",
    category: "laptop",
    model: "MSI Modern 14 B11MOU-1034VN",
    color: null,
    serial_number: "SN-SL.MSI8-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: i5-1155G7 | RAM: 16 GB | VGA: Intel Iris Xe Graphics | SSD: 512 GB",
    department: "General",
  },
  {
    id: "6fb6e407-ec03-4e74-adbd-10dc144c4521",
    asset_code: "SL.MSI20",
    product_name: "MSI Modern 14 B11MOU-1034VN",
    category: "laptop",
    model: "MSI Modern 14 B11MOU-1034VN",
    color: null,
    serial_number: "SN-SL.MSI20-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: i5-1155G7 | RAM: 8 GB | VGA: Intel Iris Xe Graphics | SSD: 512 GB",
    department: "General",
  },
  {
    id: "76f235a4-b323-4d28-8a6e-9974bc22e7d5",
    asset_code: "SL.MSI22",
    product_name: "MSI Modern 14 B11MOU-1034VN",
    category: "laptop",
    model: "MSI Modern 14 B11MOU-1034VN",
    color: null,
    serial_number: "SN-SL.MSI22-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: i5-1155G7 | RAM: 8 GB | VGA: Intel Iris Xe Graphics | SSD: 512 GB",
    department: "General",
  },
  {
    id: "79cbe655-fc99-4343-8d6b-a3a435da168b",
    asset_code: "SL.MSI23",
    product_name: "MSI Stealth 15M",
    category: "laptop",
    model: "MSI Stealth 15M",
    color: null,
    serial_number: "SN-SL.MSI23-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: Core I7-11375H | RAM: 16 GB | VGA: NVIDIA GeForce RTX 3060 | SSD: 512 Gb",
    department: "General",
  },
  {
    id: "7bf859e9-9d71-46a5-9c53-a435cd442625",
    asset_code: "SL.MAC14",
    product_name: "Macbook trắng",
    category: "laptop",
    model: "Macbook trắng",
    color: null,
    serial_number: "SN-SL.MAC14-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes: null,
    department: "General",
  },
  {
    id: "7e63ca90-462a-49d8-a5aa-e1d79c31cbd0",
    asset_code: "SL.THI3",
    product_name: "Thinkpad T15 Gen 2",
    category: "laptop",
    model: "Thinkpad T15 Gen 2",
    color: null,
    serial_number: "SN-SL.THI3-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: i5-1145G7 | RAM: 16 GB | VGA: Intel Iris Xe Graphics | SSD: 512 GB",
    department: "General",
  },
  {
    id: "82c3ca76-ca3e-4c98-af44-448dbbe172ee",
    asset_code: "SL.DEL1",
    product_name: "Dell Inspiron 15-5510",
    category: "laptop",
    model: "Dell Inspiron 15-5510",
    color: null,
    serial_number: "SN-SL.DEL1-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: i5-11320H | RAM: 16 GB | VGA: Intel Iris Xe Graphics | SSD: 512 GB",
    department: "General",
  },
  {
    id: "84c48d3c-3790-47c1-81e1-5338bc208d1b",
    asset_code: "SL.PC6",
    product_name: "PC T5500 seris",
    category: "desktop",
    model: "PC T5500 seris",
    color: null,
    serial_number: "SN-SL.PC6-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: X5650 | RAM: 16 GB | VGA: Quadro K5000 | SSD: 128 GB | HDD: 2 TB",
    department: "General",
  },
  {
    id: "9055e2cb-57f5-4550-b71d-17ff6ba70825",
    asset_code: "SL.THI25",
    product_name: "ThinkPad T470",
    category: "laptop",
    model: "ThinkPad T470",
    color: null,
    serial_number: "SN-SL.THI25-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: I7-7600U | RAM: 8 GB | VGA: Intel HD Graphics 620 | SSD: 256 GB",
    department: "General",
  },
  {
    id: "93d78470-f8e1-4146-8ae5-86430f7adc78",
    asset_code: "SL.DEL2",
    product_name: "Dell Inspiron 15-3511",
    category: "laptop",
    model: "Dell Inspiron 15-3511",
    color: null,
    serial_number: "SN-SL.DEL2-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: i5-1135G7 | RAM: 8 GB | VGA: NVIDIA GeForce MX350 | SSD: 256 GB",
    department: "General",
  },
  {
    id: "949dd8c2-4d7a-4d39-a3eb-cc94a2954b04",
    asset_code: "SL.THI17",
    product_name: "Lenovo Thinkpad T145",
    category: "laptop",
    model: "Lenovo Thinkpad T145",
    color: null,
    serial_number: "SN-SL.THI17-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes: "CPU: I5-10210U | RAM: 16 GB | VGA: Integrated | SSD: 256 GB",
    department: "General",
  },
  {
    id: "99f8ba6a-2732-4f34-9baa-14017715045d",
    asset_code: "SL.THI12",
    product_name: "Thinkpad T470S",
    category: "laptop",
    model: "Thinkpad T470S",
    color: null,
    serial_number: "SN-SL.THI12-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: I5-7300U | RAM: 8 GB | VGA: Intel HD Graphics 620 | SSD: 256 Gb",
    department: "General",
  },
  {
    id: "a8cbb61f-6d3b-49ef-9b70-201fbea0e273",
    asset_code: "SL.MSI7",
    product_name: "MSI Modern 14 B11MOU-1034VN",
    category: "laptop",
    model: "MSI Modern 14 B11MOU-1034VN",
    color: null,
    serial_number: "SN-SL.MSI7-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: i5-1155G7 | RAM: 16 GB | VGA: Intel Iris Xe Graphics | SSD: 512 GB",
    department: "General",
  },
  {
    id: "c08b870a-7d51-4abc-a1eb-3dabef7315f9",
    asset_code: "SL.MAC27",
    product_name: "Mac mini 2020",
    category: "laptop",
    model: "Mac mini 2020",
    color: null,
    serial_number: "SN-SL.MAC27-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes: "VGA: Apple M1 GPU",
    department: "General",
  },
  {
    id: "c4d3d21d-e866-4516-9916-38a84b9c7c6f",
    asset_code: "SL.MAC19",
    product_name: "Macbook MBA M1",
    category: "laptop",
    model: "Macbook MBA M1",
    color: null,
    serial_number: "SN-SL.MAC19-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes: null,
    department: "General",
  },
  {
    id: "d3912c4e-f755-4181-ba51-628003fbd97d",
    asset_code: "SL.THI13",
    product_name: "ThinkPad T470",
    category: "laptop",
    model: "ThinkPad T470",
    color: null,
    serial_number: "SN-SL.THI13-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: I7-7600U | RAM: 8 GB | VGA: Intel HD Graphics 620 | SSD: 256 GB",
    department: "General",
  },
  {
    id: "dde679b9-f8fd-4f20-a8b0-4860b595281f",
    asset_code: "SL.THI5",
    product_name: "Thinkpad T14 Gen 2",
    category: "laptop",
    model: "Thinkpad T14 Gen 2",
    color: null,
    serial_number: "SN-SL.THI5-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: AMD Ryzen 7 Pro 5850 | RAM: 32 GB | VGA: Integrated AMD Radeon Graphics | SSD: 512 GB",
    department: "General",
  },
  {
    id: "efe3c7e0-1ad1-4670-87f4-776af1a3f84a",
    asset_code: "SL.THI10",
    product_name: "ThinkPad T470",
    category: "laptop",
    model: "ThinkPad T470",
    color: null,
    serial_number: "SN-SL.THI10-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: I7-7600U | RAM: 8 GB | VGA: Intel HD Graphics 620 | SSD: 256 GB",
    department: "General",
  },
  {
    id: "f14c86c1-2a0d-44bf-82c6-2ce3674fb1fc",
    asset_code: "SL.THI11",
    product_name: "Thinkpad T470S",
    category: "laptop",
    model: "Thinkpad T470S",
    color: null,
    serial_number: "SN-SL.THI11-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes:
      "CPU: I5-7300U | RAM: 8 GB | VGA: Intel HD Graphics 620 | SSD: 256 Gb",
    department: "General",
  },
  {
    id: "fa40f541-1205-462b-ba8b-0470bcb535f2",
    asset_code: "SL.MAC16",
    product_name: "Macbook Pro 13 inch 2020",
    category: "laptop",
    model: "Macbook Pro 13 inch 2020",
    color: null,
    serial_number: "SN-SL.MAC16-202601",
    purchase_price: null,
    purchase_date: null,
    warranty_period: null,
    warranty_expiry_date: null,
    status: "available",
    current_user_employee_code: null,
    location: "Kho",
    notes: "CPU: M1 | RAM: 16 GB | VGA: Apple M1 GPU | SSD: 256 GB",
    department: "General",
  },
];

async function seedAssets() {
  try {
    console.log(`📊 Đang seed ${ASSETS_DATA.length} tài sản vào Supabase...`);

    const batchSize = 50;
    let successCount = 0;

    for (let i = 0; i < ASSETS_DATA.length; i += batchSize) {
      const batch = ASSETS_DATA.slice(i, i + batchSize);
      const batchNum = Math.floor(i / batchSize) + 1;
      const totalBatches = Math.ceil(ASSETS_DATA.length / batchSize);

      try {
        const { error } = await supabase
          .from("assets")
          .upsert(batch, { onConflict: "id" });

        if (error) {
          console.error(
            `❌ Lỗi lô ${batchNum}/${totalBatches}:`,
            error.message,
          );
          throw error;
        }

        successCount += batch.length;
        console.log(
          `✅ Lô ${batchNum}/${totalBatches} hoàn thành (${batch.length} bản ghi)`,
        );
      } catch (batchError) {
        console.error(`❌ Lỗi xảy ra ở lô ${batchNum}:`, batchError.message);
        throw batchError;
      }
    }

    console.log(
      `\n✅ Seed thành công! ${successCount} tài sản đã được thêm vào Supabase`,
    );
  } catch (error) {
    console.error("❌ Seed thất bại:", error.message);
    process.exit(1);
  }
}

seedAssets();
